mode: backtest # backtest, live
start_date: 2025-08-30
end_date: 2025-09-04
primary_interval: 1h
initial_cash: 100000
margin_requirement: 0.0
show_reasoning: false
show_agent_graph: true
signals:
  intervals: ["30m", "1h", "4h"]
  tickers: ["BTCUSDT", "ETHUSDT"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]
model:
  name: "gpt-4o-mini"
  provider: "openai"
#  base_url: "https://api.openai.com/v1"  #
